//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IHD_CR
    {
        public long RID { get; set; }
        public string FullName { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        public string Position { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public string Type { get; set; }
        public string MailStatus { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string CandidateStatus { get; set; }
    }
}
