//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHD_Tabusers
    {
        public long RID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long LocationID { get; set; }
        public long Status { get; set; }
        public string EmailID { get; set; }
    }
}
