//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personal_data()
        {
            this.IHD_TABDOCS = new HashSet<IHD_TABDOCS>();
        }
    
        public long RID { get; set; }
        public string contactperson { get; set; }
        public decimal expsalary { get; set; }
        public Nullable<System.DateTime> Availonboard { get; set; }
        public Nullable<System.DateTime> Datetimetomeet { get; set; }
        public string Posdesire { get; set; }
        public string Preferloc { get; set; }
        public decimal CurrentCTC { get; set; }
        public string Placetomeet { get; set; }
        public string name { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Phone_ { get; set; }
        public string Gender { get; set; }
        public System.DateTime Dob { get; set; }
        public int Age { get; set; }
        public string Maritalstatus { get; set; }
        public Nullable<bool> FLAG { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Created_User { get; set; }
        public string Modified_User { get; set; }
        public string Country { get; set; }
        public string LanguagesKnown { get; set; }
        public string Careeraspirations { get; set; }
        public string strengthsandweakness { get; set; }
        public string HowKnowAboutCollabera { get; set; }
        public string WhatKnownAboutCollabera { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> CRRID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHD_TABDOCS> IHD_TABDOCS { get; set; }
    }
}
