//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recent_Employeer
    {
        public long RID { get; set; }
        public string position { get; set; }
        public string company { get; set; }
        public System.DateTime fromdate { get; set; }
        public System.DateTime todate { get; set; }
        public string skills { get; set; }
        public Nullable<long> resid { get; set; }
    }
}
