//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public long RID { get; set; }
        public string name { get; set; }
        public string relationship { get; set; }
        public string contactno { get; set; }
        public Nullable<long> resid { get; set; }
    }
}
